<<<<<<< HEAD
apiVersion: v1
kind: Secret
metadata:
  name: cred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ2YWxheHkwNS5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiYkc5bmFXNTBiMkYzYzBCbmJXRnBiQzVqYjIwNlZtRnNZWGg1UURFeU13PT0iCgkJfQoJfQp9
=======
apiVersion: v1
kind: Secret
metadata:
  name: cred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ2YWxheHkwNS5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiYkc5bmFXNTBiMkYzYzBCbmJXRnBiQzVqYjIwNlZtRnNZWGg1UURFeU13PT0iCgkJfQoJfQp9
>>>>>>> 43f90fbbd2f7e7dec39931129f75a7acd15774f7
type: kubernetes.io/dockerconfigjson