<<<<<<< HEAD
apiVersion: v1
kind: Service
metadata:
  name:  valaxy-rtp-service
  namespace: valaxy
spec:
  type: NodePort
  selector:
    app: valaxy-rtp
  ports:
  - nodePort: 30082
    port: 8000
=======
apiVersion: v1
kind: Service
metadata:
  name:  valaxy-rtp-service
  namespace: valaxy
spec:
  type: NodePort
  selector:
    app: valaxy-rtp
  ports:
  - nodePort: 30082
    port: 8000
>>>>>>> 43f90fbbd2f7e7dec39931129f75a7acd15774f7
    targetPort: 8000